"""Fail when a submitted figure is older than the generator that writes it.

This exists because of a defect that shipped. An axis-unit correction was applied to
`fig_nuts3_map.py`, the commit rebuilt ten other figures, and this one was not rebuilt.
A grep of the source said the unit was fixed; the compiled manuscript still printed the
old one, on the colourbar of a full-page map, contradicting its own caption two lines
below. Nothing caught it: the print-scale gate measures glyph size, the overlap gate
compares text against text, and the number gate reads CSVs. None of them asks the only
question that mattered, which is whether the artwork on the page was built from the code
in the repository.

The rule was mtime, and mtime was wrong twice over. Git does not preserve it, so on any
fresh clone the gate compared two arbitrary numbers; and after that was patched to take
the later of commit time and mtime, committing a generator gave it a timestamp later than
the mtime of every figure that had regenerated byte-identically, so the tip of the branch
reported three false positives under a commit message saying the suite passed.

Timestamps cannot answer the question. "Not regenerated" and "regenerated to the same
bytes" look identical to a clock. So the gate now hashes the generator's source together
with every in-repo module it imports, transitively, and compares that against a hash
recorded beside the figures when they were last built. Same content, same hash, on any
machine and any checkout.

What this still cannot catch: a generator edited and re-recorded without regenerating.
That is a deliberate act, where the timestamp version failed by accident.

Run:   cd code && PYTHONPATH=. python -m scripts.check_figure_freshness
Build: the same command with --record, immediately after regenerating the figures
Exit:  non-zero if any submitted figure was built from different source than it carries.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FIGDIR = REPO / "paper" / "figs" / "paper"
PROV = FIGDIR / "PROVENANCE.json"
SCRIPTS = Path(__file__).resolve().parent

# Only the figures the two submitted documents actually include. A stale figure nobody
# prints is not a defect worth failing a build over.
DOCS = [REPO / "paper" / "ae_submission" / "sections",
        REPO / "paper" / "ae_submission" / "si_body"]
ROOTS = [REPO / "paper" / "ae_submission" / "V7.tex",
         REPO / "paper" / "ae_submission" / "SI.tex"]

INC = re.compile(r"\\includegraphics\[[^\]]*\]\{([^}]+)\}")


def included() -> set:
    names = set()
    for d in DOCS:
        for f in sorted(d.glob("*.tex")):
            names |= set(INC.findall(f.read_text(encoding="utf-8")))
    for f in ROOTS:
        if f.exists():
            names |= set(INC.findall(f.read_text(encoding="utf-8")))
    return {Path(n).stem for n in names}


def writers() -> dict:
    """stem -> every script that names it.

    A figure is often written by one module and re-exported by another, and both can
    change what it draws, so the caller hashes all of them rather than choosing one."""
    out = {}
    for s in sorted(SCRIPTS.glob("*.py")):
        if s.name.startswith("check_"):
            continue
        try:
            txt = s.read_text(encoding="utf-8")
        except Exception:
            continue
        for stem in included():
            if stem in txt:
                out.setdefault(stem, []).append(s)
    return out


def _imports(src: str) -> set:
    """In-repo modules this source imports, by dotted name. One level; the closure walks."""
    names = set()
    for m in re.finditer(r"^\s*(?:from|import)\s+([\w.]+)", src, re.M):
        names.add(m.group(1))
    return names


def _module_path(dotted: str):
    """Map a dotted name onto a file under code/, or None if it is not ours."""
    parts = dotted.split(".")
    for base in (SCRIPTS.parent, SCRIPTS):
        cand = base.joinpath(*parts).with_suffix(".py")
        if cand.exists():
            return cand
    return None


def closure(script: Path) -> list:
    """The script plus every in-repo module it reaches, transitively, sorted.

    A figure's content depends on its generator AND on what that generator imports. The
    unit conversion that started this whole gate lived in a helper; editing _figstyle.py
    or src/Economics.py changes what every figure draws and used to mark nothing stale.
    """
    seen, stack = set(), [script]
    while stack:
        f = stack.pop()
        if f in seen or not f.exists():
            continue
        seen.add(f)
        try:
            src = f.read_text(encoding="utf-8")
        except Exception:
            continue
        for dotted in _imports(src):
            m = _module_path(dotted)
            if m is not None:
                stack.append(m)
    return sorted(seen)


def source_hash(scripts) -> str:
    """sha256 over every generator that writes this figure, and their import closures.

    This took one script, the alphabetically last of those naming the stem, and that was
    wrong in the one case the gate exists for. Two modules name P01_nuts3_map;
    paper_figures.py sorts after fig_nuts3_map.py, so the hash covered paper_figures.py,
    while rebuild_local.py runs fig_nuts3_map.py second and it therefore writes the
    shipped PDF. Editing the real generator of the map was silent, and the map's
    colourbar unit is the defect this whole gate was written for.

    Take the union. A figure is stale if ANY module that writes it has changed, and
    which one wrote it last is not something the gate should have to guess.
    """
    if isinstance(scripts, Path):
        scripts = [scripts]
    h = hashlib.sha256()
    seen = set()
    for s in sorted(scripts, key=lambda p: p.name):
        for f in closure(s):
            if f in seen:
                continue
            seen.add(f)
    for f in sorted(seen, key=lambda p: p.as_posix()):
        h.update(f.relative_to(REPO).as_posix().encode())
        h.update(f.read_bytes())
    return h.hexdigest()[:16]


def record() -> int:
    """Write the provenance sidecar. Run immediately after regenerating figures."""
    w = writers()
    out = {}
    for stem in sorted(included()):
        if stem not in w:
            continue
        out[stem] = {"generator": ", ".join(sorted(x.name for x in w[stem])),
                     "hash": source_hash(w[stem])}
    PROV.write_text(json.dumps(out, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(f"recorded provenance for {len(out)} figure(s) -> {PROV.relative_to(REPO)}")
    return 0


def main() -> int:
    if "--record" in sys.argv:
        return record()
    if not PROV.exists():
        print(f"no provenance sidecar at {PROV.relative_to(REPO)}; "
              f"run this module with --record after building the figures.")
        return 1
    prov = json.loads(PROV.read_text(encoding="utf-8"))
    stale, w, checked = [], writers(), 0
    for stem in sorted(included()):
        pdf = FIGDIR / (stem + ".pdf")
        # Neither of these is a skip. The print-scale gate had the same hole and it was
        # closed there: an inclusion nobody can check has not been checked, and printing
        # "11 checked" while silently passing over two of them is a false report.
        if not pdf.exists():
            stale.append((stem, "no figure PDF on disk"))
            continue
        if stem not in w:
            stale.append((stem, "no generator in code/scripts names this figure"))
            continue
        checked += 1
        want = prov.get(stem, {}).get("hash")
        got = source_hash(w[stem])
        if want is None:
            stale.append((stem, "no recorded provenance"))
        elif want != got:
            stale.append((stem, ", ".join(sorted(x.name for x in w[stem]))))

    if stale:
        print(f"{len(stale)} submitted figure(s) built from different source than they carry:")
        for stem, script in stale:
            print(f"  {stem:34s} source changed: {script}")
        print("\nRegenerate them and re-run with --record, or the page will disagree with "
              "the source.")
        return 1
    print(f"Every submitted figure was built from the source it carries "
          f"({checked} checked, hashed over each generator's import closure).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
