"""T5(a) -- global (Sobol) sensitivity of EU 2050 useful heat demand.

The paper's tornado (fig9) is a one-at-a-time screen of 2030 CO2 to the cost/
emissions axes. This adds a proper VARIANCE-BASED global sensitivity for the
headline demand result, decomposing the variance of EU 2050 useful heat across
its four uncertain drivers:
  - envelope-rate multiplier  (the scenario lever; +/-35% band on the per-country
    STATED_POLICIES envelope-renovation rate);
  - population multiplier      (EUROPOP/ONS/BFS projection uncertainty);
  - occupancy multiplier       (household-size trend uncertainty);
  - dwelling-size multiplier   (held flat centrally; small upside risk).

EU 2050 demand depends only on these (not on prices/tech mix), so it is computed
analytically per country -- D_c = base_c * pop_r_c*pop_m * occ_r_c*occ_m * size_m
* (1 - clip(r_c*rate_m))^25 -- making a full Saltelli/Sobol design (N>=2048,
~10k evaluations) instantaneous. First-order (S1) and total (ST) Sobol indices
are reported via SALib. (The cost/emissions axes -- carbon price, H2 trajectory,
discount rate, ETS2 pass-through, fuel-price correlation -- act through the
LCOH/tech-mix layer, whose global screen is compute-bound on the full NUTS3 MC;
the existing one-at-a-time tornado covers them and a full Morris screen is the
documented next step.)

Run:  cd code && PYTHONPATH=. python -m scripts.global_sensitivity
Out:  code/results/global_sensitivity.csv + console
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from SALib.sample import saltelli
from SALib.analyze import sobol

# Fixed seed for the Sobol bootstrap so the confidence intervals, and hence this
# script's CSV, regenerate identically. Matches src.Config.RNG_SEED.
SEED = 42

import src.Config as C
from src.Config import PROCESSED_DIR, RESULTS_DIR, forward_demand_ratio


def _base_and_drivers():
    stock = pd.read_csv(PROCESSED_DIR / "building_stock_nuts3_bottomup.csv")
    base = (stock.groupby("country")["heat_2015_MWh"].sum() / 1e6).to_dict()  # TWh
    rates = C.central_country_intensity_rates("STATED_POLICIES")
    countries = [c for c in base if c in rates]
    base_c = np.array([base[c] for c in countries])
    # pop_r * occ_r (stock growth, rate-independent) per country
    popocc = np.array([forward_demand_ratio(c, 2050, 0.0) for c in countries])
    r_c = np.array([rates[c] for c in countries])
    return base_c, popocc, r_c


def main() -> None:
    base_c, popocc, r_c = _base_and_drivers()

    problem = {
        "num_vars": 4,
        "names": ["envelope_rate_mult", "population_mult", "occupancy_mult",
                  "dwelling_size_mult"],
        "bounds": [[0.65, 1.35], [0.97, 1.03], [0.95, 1.05], [0.98, 1.05]],
    }
    X = saltelli.sample(problem, 2048, calc_second_order=False)

    def eu_demand(p):
        rate_m, pop_m, occ_m, size_m = p
        intens = np.clip(r_c * rate_m, 0.0, 0.05)
        # popocc already = pop_r*occ_r; scale by the sampled multipliers
        d = base_c * popocc * pop_m * occ_m * size_m * (1 - intens) ** 25
        return float(d.sum())

    Y = np.array([eu_demand(p) for p in X])
    # Seed the bootstrap. The S1/ST indices are deterministic given the Saltelli
    # design, but the confidence intervals are resampled, so without a seed this CSV
    # never regenerated byte-identically and looked like a reproducibility failure.
    Si = sobol.analyze(problem, Y, calc_second_order=False, print_to_console=False,
                       seed=SEED)

    df = pd.DataFrame({"driver": problem["names"],
                       "S1": np.round(Si["S1"], 3),
                       "S1_conf": np.round(Si["S1_conf"], 3),
                       "ST": np.round(Si["ST"], 3),
                       "ST_conf": np.round(Si["ST_conf"], 3)}).sort_values("ST", ascending=False)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(RESULTS_DIR / "global_sensitivity.csv", index=False)
    print(f"EU 2050 useful heat demand: mean {Y.mean():.0f} TWh, "
          f"sd {Y.std():.0f} TWh, 5-95% [{np.percentile(Y,5):.0f}-{np.percentile(Y,95):.0f}]")
    print("Sobol indices (S1 first-order, ST total) over the demand drivers:")
    print(df.to_string(index=False))
    top = df.iloc[0]
    print(f"\nDominant driver: {top.driver} (ST={top.ST:.2f}) -- the envelope "
          f"renovation rate (the scenario lever) governs most of the EU 2050 "
          f"demand variance; population, occupancy and dwelling size are secondary.")
    print(f"Wrote {RESULTS_DIR / 'global_sensitivity.csv'}")


if __name__ == "__main__":
    main()
