"""The INFRASTRUCTURE BILL of each pathway -- transmission/distribution deepening.

Each heating pathway carries a different wires-and-pipes bill that the LCOH comparison
only ever shows per-MWh. This script makes it explicit in bn EUR, per country x scenario,
from the model's own outputs (2025 -> 2050 technology shifts) and the network cost bands
already in Economics:

  ELECTRICITY distribution reinforcement: added HP electric peak (Delta HP share x heat
    peak_GW / COP_peak x coincidence 0.5) x EUR/kW-peak band (400/800/1600).
  DISTRICT-HEAT expansion: Delta DH share x dwellings x EUR/connection band
    (3000/5000/8000; DEA technology catalogue, Heat Roadmap Europe network+branch costs).
  HYDROGEN network: H2-2050 share x dwellings x the per-country blend cost
    (gas-grid-coverage-weighted convert/newbuild bands from Economics).

Dwelling counts come from the bottom-up stock's dwellings estimate (calibrated to census
MFH shares; levels run ~20-30% high in some countries -- a level bias that cancels in the
cross-scenario comparison and is dominated by the ~2x cost-band uncertainty).

Run: cd code && PYTHONPATH=. python -m scripts.infrastructure_bill
Out: results/infrastructure_bill.csv + figure F16.
"""
from __future__ import annotations
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
from pathlib import Path
from src.Config import RESULTS_DIR, PROCESSED_DIR
from src.Economics import (ELEC_REINFORCE_EUR_PER_KW_PEAK, ELEC_REINFORCE_COINCIDENCE,
                           ELEC_REINFORCE_COP_PEAK, H2_DIST_CONVERT_RANGE,
                           H2_DIST_NEWBUILD_RANGE)
from src.Policy import GAS_GRID_COVERAGE
from scripts._figstyle import set_style, short_scen, legend_below
set_style()

REPO = Path(__file__).resolve().parents[2]
FIG = REPO / "paper" / "figs" / "diagnostics"; FIG.mkdir(parents=True, exist_ok=True)
SCEN = ["CURRENT_POLICIES", "STATED_POLICIES", "NET_ZERO", "H2_PUSH"]
DH_CONNECTION_EUR = {"low": 3000.0, "central": 5000.0, "high": 8000.0}


def shares(sc, year):
    d = pd.read_csv(RESULTS_DIR / f"mc_country_{sc}.csv")
    d = d[(d.variable == "tech_share") & (d.year == year)]
    piv = d.pivot_table(index="country", columns="tech", values="q50", aggfunc="sum").fillna(0)
    piv = piv.div(piv.sum(axis=1).replace(0, 1), axis=0)   # renormalise q50
    out = pd.DataFrame(index=piv.index)
    out["hp"] = piv.get("hp_air", 0) + piv.get("hp_ground", 0)
    out["dh"] = piv.get("district_heat", 0)
    out["h2"] = piv.get("h2_boiler", 0)
    return out


SI_TAB = REPO / "paper" / "ae_submission" / "si_body" / "_tab_infra_bill.tex"
SCEN_LABEL = {"CURRENT_POLICIES": "Current Policies", "STATED_POLICIES": "Stated Policies",
              "NET_ZERO": "Net Zero", "H2_PUSH": "H2 Push"}


def emit_si_table(eu: pd.DataFrame) -> None:
    """Write the study-area bill by scenario as a LaTeX table for the Supplementary
    Information. The conclusion of the submission quotes this range, so the table is
    what the reader checks it against."""
    rows = "\n".join(
        f"{SCEN_LABEL[sc]} & {eu.loc[sc].elec_bn_central:.0f} & "
        f"{eu.loc[sc].dh_bn_central:.0f} & {eu.loc[sc].h2_bn_central:.0f} & "
        f"{eu.loc[sc].total_bn_central:.0f} & "
        f"{eu.loc[sc].total_bn_low:.0f} to {eu.loc[sc].total_bn_high:.0f} \\\\"
        for sc in SCEN)
    lo = eu.total_bn_central.min()
    hi = eu.total_bn_central.max()
    h2p = eu.loc["H2_PUSH"]
    SI_TAB.write_text(rf"""% Generated by scripts.infrastructure_bill -- do not edit by hand.
\begin{{table}}[htbp]
\centering
\footnotesize
\caption{{\textbf{{Cumulative network investment, 2025 to 2050, across the 29
markets.}} In bn~\euro{{}}, by pathway and by network. The central column uses the mid cost band
for each network; the final column carries the low and high bands. On the central band
the pathways span \euro{{}}{lo:.0f} to {hi:.0f}~bn. Each cell is rounded independently, so a
row's three networks can sum to one short of its own total. The \euro{{}}{h2p.h2_bn_central:.0f}~bn
hydrogen network in H2 Push sits alongside, and does not displace,
\euro{{}}{h2p.elec_bn_central:.0f}~bn of electricity reinforcement in the same pathway.}}
\label{{tab:infra_bill}}
\begin{{tabular}}{{lrrrrr}}
\toprule
Pathway & Electricity & District heat & H$_2$ network & Total (central) & Total (low to high) \\
\midrule
{rows}
\bottomrule
\end{{tabular}}
\\[2pt]{{\footnotesize\textit{{Source: Authors' contribution.}}}}
\end{{table}}
""")
    print(f"Wrote {SI_TAB}")


def main():
    lp = pd.read_csv(RESULTS_DIR / "heat_load_profile.csv").set_index("country")
    stock = pd.read_csv(PROCESSED_DIR / "building_stock_nuts3_bottomup.csv")
    dw = (stock[stock.building_type.isin(["SFH", "MFH_HIGH"])]
          .groupby("country").dwellings_2021.sum())

    rows = []
    for sc in SCEN:
        s50, s25 = shares(sc, 2050), shares(sc, 2025)
        for c in s50.index:
            if c not in lp.index or c not in dw.index:
                continue
            d_hp = max(s50.loc[c, "hp"] - s25.loc[c, "hp"], 0)
            d_dh = max(s50.loc[c, "dh"] - s25.loc[c, "dh"], 0)
            h2_50 = s50.loc[c, "h2"]
            # electricity: added coincident electric peak from new HP load
            add_peak_gw = lp.loc[c, "peak_GW"] * d_hp / ELEC_REINFORCE_COP_PEAK * ELEC_REINFORCE_COINCIDENCE
            cov = GAS_GRID_COVERAGE.get(c, 0.30)
            r = {"country": c, "scenario": sc,
                 "added_hp_peak_GW": round(add_peak_gw, 2),
                 "new_dh_connections_M": round(d_dh * dw[c] / 1e6, 2),
                 "h2_connections_M": round(h2_50 * dw[c] / 1e6, 2)}
            for b in ("low", "central", "high"):
                elec_bn = add_peak_gw * 1e6 * ELEC_REINFORCE_EUR_PER_KW_PEAK[b] / 1e9
                dh_bn = d_dh * dw[c] * DH_CONNECTION_EUR[b] / 1e9
                h2_per_conn = cov * H2_DIST_CONVERT_RANGE[b] + (1 - cov) * H2_DIST_NEWBUILD_RANGE[b]
                h2_bn = h2_50 * dw[c] * h2_per_conn / 1e9
                r[f"elec_bn_{b}"] = round(elec_bn, 2)
                r[f"dh_bn_{b}"] = round(dh_bn, 2)
                r[f"h2_bn_{b}"] = round(h2_bn, 2)
                r[f"total_bn_{b}"] = round(elec_bn + dh_bn + h2_bn, 2)
            rows.append(r)
    df = pd.DataFrame(rows)
    df.to_csv(RESULTS_DIR / "infrastructure_bill.csv", index=False)

    eu = df.groupby("scenario")[[f"{k}_bn_central" for k in ("elec", "dh", "h2", "total")]
                                + ["total_bn_low", "total_bn_high"]].sum().reindex(SCEN)
    print("EU infrastructure bill, cumulative 2025-2050 (bn EUR, central [low-high]):")
    print(f"{'scenario':<18}{'electricity':>12}{'district heat':>14}{'H2 network':>11}{'TOTAL':>22}")
    for sc in SCEN:
        r = eu.loc[sc]
        print(f"{sc:<18}{r.elec_bn_central:>12.0f}{r.dh_bn_central:>14.0f}{r.h2_bn_central:>11.0f}"
              f"{r.total_bn_central:>10.0f} [{r.total_bn_low:.0f}-{r.total_bn_high:.0f}]")

    emit_si_table(eu)

    # figure: stacked EU bill by scenario with low-high whiskers
    fig, ax = plt.subplots(figsize=(7.6, 4.8))
    x = np.arange(len(SCEN))
    parts = [("elec_bn_central", "Electricity reinforcement", "#08519c"),
             ("dh_bn_central", "District-heat expansion", "#e6550d"),
             ("h2_bn_central", "Hydrogen network", "#6a51a3")]
    bottom = np.zeros(len(SCEN))
    for col, lab, c in parts:
        v = eu[col].values
        ax.bar([short_scen(s) for s in SCEN], v, bottom=bottom, color=c, label=lab)
        bottom += v
    ax.errorbar(x, eu.total_bn_central, fmt="none",
                yerr=[eu.total_bn_central - eu.total_bn_low, eu.total_bn_high - eu.total_bn_central],
                ecolor="#333", capsize=4, lw=1.4)
    ax.set_ylabel("Cumulative network investment 2025–2050 (bn €)")
    ax.set_title("The infrastructure bill of each pathway (EU+UK+CH)")
    plt.setp(ax.get_xticklabels(), rotation=12, ha="right")
    legend_below(ax, ncol=3)
    fig.savefig(FIG / "F16_infrastructure_bill.png"); plt.close(fig)
    print("\nWrote results/infrastructure_bill.csv + F16_infrastructure_bill.png")


if __name__ == "__main__":
    main()
