"""Test whether the heat-pump flexibility bound is a result or a restatement.

WHY THIS EXISTS. The paper reports that shifting up to 30 per cent of the heat-pump load
across a window of up to 13 hours cuts the firm peaking fleet by at most about 11 per
cent, and it explains that modest number as follows: "the binding event is a multi-day
wind lull rather than an evening peak, and no amount of intra-day pre-heating moves load
out of a six-day window."

A referee pointed out that this explanation is a restatement of one line of the model.
The dispatch imposes a single synthetic cold-and-still event whose length is hard-coded
at six days (power_dispatch.COLD_SNAP_DAYS), and the heat spike and the wind lull both
run on that same window in all 29 countries at once. The flexibility sweep varied the
operator (phi, the window, and three kernels) but never varied the one parameter that
the sentence itself identifies as decisive. On that reading the bound was a property of
the assumption rather than a finding, and the objection was correct.

WHAT THIS SWEEPS. The event duration, over {2, 4, 6, 10} days, holding everything else
exactly as the headline run holds it: same seeds, same country order, same generator
advance, same firm gas fleet, same three-hour standard, same Dunkelflaute depth. For
each duration it computes the inflexible fleet and the fleet under the most generous
flexibility corner the paper reports (phi = 0.30, window = 13 h, one-sided pre-heat,
which is the kernel that reduces the fleet most), and reports the reduction.

HOW TO READ IT. If the reduction is roughly flat across durations then the bound really
is a property of the multi-day event and the paper's explanation stands. If it climbs
sharply as the event shortens then the bound is a function of the assumed duration, and
the honest statement is that a shorter or less correlated event would give a materially
larger reduction. Either way the answer belongs in the paper, because at present the
6-day column is the only one a reader can see.

Note that the inflexible fleet itself moves with duration, so the reduction is always
taken against the baseline at the SAME duration. Comparing a 2-day flexible fleet to the
6-day inflexible one would confound the two effects.

Run:  cd code && PYTHONPATH=. python -m scripts.cold_snap_duration_sweep
Out:  code/results/cold_snap_duration_sweep.csv
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.Config import RESULTS_DIR
import scripts.power_dispatch as pdis
from scripts.hp_flexibility_bound import run_case, SCEN, BASIS, YEAR

# The generous corner the manuscript carries as its bound.
PHI, WINDOW, KERNEL = 0.30, 13, "preheat"


SI_TAB = (Path(__file__).resolve().parents[2] / "paper" / "ae_submission" / "si_body"
          / "_tab_snap_duration.tex")


def emit_si_table(df: "pd.DataFrame", central_days: int) -> None:
    """Write the SI table from the sweep itself.

    It was hand-written, and its caption asserted a +/-10 per cent band against the
    +8.8/-8.6 per cent its own rows give -- prose sitting directly above the numbers that
    refute it, in a file no gate compared with the CSV. Generated here so the two cannot part.
    """
    c = df[df.cold_snap_days == central_days].iloc[0]
    lo = (df.inflexible_fleet_gw.min() / c.inflexible_fleet_gw - 1) * 100
    hi = (df.inflexible_fleet_gw.max() / c.inflexible_fleet_gw - 1) * 100
    band = max(abs(lo), abs(hi))
    rows = "\n".join(
        f"{int(r.cold_snap_days)} & {r.inflexible_fleet_gw:.1f} & {r.flexible_fleet_gw:.1f} & "
        f"{r.reduction_pct:.1f} \\\\" for _, r in df.iterrows())
    SI_TAB.write_text(rf"""% Generated by scripts.cold_snap_duration_sweep -- do not edit by hand.
\begin{{table}}[htbp]
\centering
\footnotesize
\caption{{\textbf{{Firm-capacity requirement against the assumed length of the
synthetic cold-and-still event.}} The flexibility reduction stays nearly flat across a
fivefold change in event length, so the {c.inflexible_fleet_gw:.0f}~GW headline carries
about $\pm${band:.0f}~per~cent from this choice alone.}}
\label{{tab:snap_duration}}
\begin{{tabular}}{{rrrr}}
\toprule
Event length (days) & Inflexible fleet (GW) & Flexible fleet (GW) & Reduction (\%) \\
\midrule
{rows}
\bottomrule
\end{{tabular}}
\\[2pt]{{\footnotesize\textit{{Source: Authors' contribution.}}}}
\end{{table}}
""")
    print(f"Wrote {SI_TAB}")


def main() -> None:
    cap = pdis.load_capacity()
    lp = pd.read_csv(RESULTS_DIR / "heat_load_profile.csv").set_index("country")
    mc = pd.read_csv(RESULTS_DIR / f"mc_country_{SCEN}.csv")
    countries = [c for c in cap if c in lp.index]

    original = pdis.COLD_SNAP_DAYS
    rows = []
    print(f"Cold-snap duration sweep, {SCEN} {YEAR}, "
          f"flexibility corner phi={PHI}, W={WINDOW} h, {KERNEL} kernel\n")
    print(f"  {'days':>5}{'inflexible GW':>16}{'flexible GW':>14}{'reduction %':>14}")
    try:
        for days in pdis.COLD_SNAP_SWEEP:
            pdis.COLD_SNAP_DAYS = days
            base_fleet, _, _ = run_case(cap, lp, mc, countries, 0.0, 3)
            flex_fleet, _, _ = run_case(cap, lp, mc, countries, PHI, WINDOW, KERNEL)
            red = 100.0 * (base_fleet - flex_fleet) / base_fleet if base_fleet else np.nan
            print(f"  {days:>5}{base_fleet:>16.1f}{flex_fleet:>14.1f}{red:>14.1f}")
            rows.append(dict(cold_snap_days=days,
                             inflexible_fleet_gw=round(base_fleet, 2),
                             flexible_fleet_gw=round(flex_fleet, 2),
                             reduction_pct=round(red, 2)))
    finally:
        pdis.COLD_SNAP_DAYS = original

    df = pd.DataFrame(rows)
    out = RESULTS_DIR / "cold_snap_duration_sweep.csv"
    df.to_csv(out, index=False)

    emit_si_table(df, original)

    central = df[df.cold_snap_days == original].reduction_pct.iloc[0]
    print(f"\n  central ({original} d): {central:.1f}% reduction")
    print(f"  across {df.cold_snap_days.min()} to {df.cold_snap_days.max()} days: "
          f"{df.reduction_pct.min():.1f} to {df.reduction_pct.max():.1f}%")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
