"""RQ1, quantified: per-country LCOH gap between a hydrogen boiler and the best
available heat pump, 2030 and 2050, under the CENTRAL hydrogen-price trajectory.

gap = LCOH(h2_boiler) - min(LCOH(hp_air), LCOH(hp_ground))   [EUR/MWh_useful]

A small/negative gap = hydrogen comes closest to (or reaches) heat-pump parity.
We rank countries by the 2050 gap and attach the three structural drivers the
paper argues for: residential electricity price (raises HP LCOH), gas-grid
coverage (lowers H2 distribution cost), and heat-pump feasibility (low feasibility
preserves a niche). This turns the qualitative RQ1 "conditions" list into a
model-grounded country ranking.

Run:  cd code && PYTHONPATH=. python -m scripts.h2_gap_analysis
Out:  code/results/h2_hp_gap.csv + console
"""
from __future__ import annotations

import pandas as pd

import src.Policy as Policy
from src.Config import PROCESSED_DIR, RESULTS_DIR
from src.Economics import compute_lcoh, get_fuel_price

COUNTRIES = ["AT", "BE", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "EL", "ES",
             "FI", "FR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT", "NL",
             "PL", "PT", "RO", "SE", "SI", "SK", "UK"]


def _hp_feasibility() -> dict:
    try:
        feas = pd.read_csv(PROCESSED_DIR / "hp_dh_feasibility_bottomup.csv")
        return feas.groupby("country")["hp_feasibility"].mean().to_dict()
    except Exception:
        return {}


def main() -> None:
    hp_feas = _hp_feasibility()
    rows = []
    for c in COUNTRIES:
        try:
            h2_30 = compute_lcoh("h2_boiler", c, 2030, h2_scenario="CENTRAL")
            h2_50 = compute_lcoh("h2_boiler", c, 2050, h2_scenario="CENTRAL")
            hp_30 = min(compute_lcoh("hp_air", c, 2030), compute_lcoh("hp_ground", c, 2030))
            hp_50 = min(compute_lcoh("hp_air", c, 2050), compute_lcoh("hp_ground", c, 2050))
        except Exception as e:
            print(f"  [skip] {c}: {e}")
            continue
        rows.append({
            "country": c,
            "gap_2030": round(h2_30 - hp_30, 1),
            "gap_2050": round(h2_50 - hp_50, 1),
            "h2_lcoh_2050": round(h2_50, 1),
            "best_hp_lcoh_2050": round(hp_50, 1),
            "elec_price_2030": round(get_fuel_price("electricity", c, 2030), 1),
            "gas_grid_coverage": round(Policy.GAS_GRID_COVERAGE.get(c, 0.30), 2),
            "hp_feasibility": round(hp_feas.get(c, float("nan")), 2),
        })
    df = pd.DataFrame(rows).sort_values("gap_2050").reset_index(drop=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(RESULTS_DIR / "h2_hp_gap.csv", index=False)

    print("H2-boiler minus best-heat-pump LCOH gap (EUR/MWh_useful, CENTRAL H2):")
    print(f"{'cc':3s} {'gap30':>6s} {'gap50':>6s} {'elec30':>7s} {'gasgrid':>7s} {'hpfeas':>6s}")
    for _, r in df.iterrows():
        print(f"{r.country:3s} {r.gap_2030:6.0f} {r.gap_2050:6.0f} "
              f"{r.elec_price_2030:7.0f} {r.gas_grid_coverage:7.2f} {r.hp_feasibility:6.2f}")
    print(f"\nNarrowest 2050 gap: {df.iloc[0].country} ({df.iloc[0].gap_2050:.0f}); "
          f"widest: {df.iloc[-1].country} ({df.iloc[-1].gap_2050:.0f}). "
          f"EU mean 2050 gap: {df.gap_2050.mean():.0f}.")
    print(f"Countries where H2 reaches parity (gap<=0) in 2050: "
          f"{(df.gap_2050 <= 0).sum()} of {len(df)}.")
    print(f"Wrote {RESULTS_DIR / 'h2_hp_gap.csv'}")
    emit_si_table(df)


# ── SI table: the headline base-load result, per country ──────────────────────
# The 22-of-29 base-load comparison is this paper's central finding and it had no table in
# either document: the submission named a handful of countries in prose and deferred the
# rest to "the public repository" eleven times, which is a GitHub repo and not an archival
# record. Written from the artefact so the table cannot drift from the count the text states.
# The header set its minus as $-$ and the body as a plain hyphen, so one table carried two
# glyphs for the same operator. Both are math minus now.
def _signed(v: float) -> str:
    return f"$-${abs(v):.1f}" if v < 0 else f"$+${v:.1f}"


def emit_si_table(df) -> None:
    d = df.sort_values("gap_2050")
    n_h2 = int((d.gap_2050 <= 0).sum())
    rows = ["% Generated by scripts.h2_gap_analysis -- do not edit by hand.",
            r"\begin{table}[htbp]", r"\centering", r"\footnotesize",
            r"\caption{\textbf{Base-load levelised cost of heat by country, 2050.} Best",
            r"available heat pump, hydrogen boiler and the gap between them, in \euro{}/MWh of",
            rf"useful heat, sorted by the gap. A negative gap means hydrogen is the cheaper of",
            rf"the two clean options, which holds in {n_h2} of the {len(d)} markets. Each median",
            r"is taken down its own column, so the median gap is the median of the per-country",
            r"gaps and not the difference of the two median costs; here those differ more than",
            r"threefold. Gaps are computed at full precision and rounded, so a printed gap can",
            r"differ by 0.1 from the difference of the two printed costs beside it.}",
            r"\label{tab:lcoh_by_country}",
            r"\begin{tabular}{lrrr}", r"\toprule",
            r"Country & Best heat pump & H$_2$ boiler & Gap (H$_2$ $-$ HP) \\",
            r"\midrule"]
    for r in d.itertuples():
        rows.append(f"{r.country} & {r.best_hp_lcoh_2050:.1f} & {r.h2_lcoh_2050:.1f} & "
                    f"{_signed(r.gap_2050)} \\\\")
    rows += [r"\midrule",
             f"Median & {d.best_hp_lcoh_2050.median():.1f} & {d.h2_lcoh_2050.median():.1f} & "
             f"{_signed(d.gap_2050.median())} \\\\",
             r"\bottomrule", r"\end{tabular}",
             r"\\[2pt]{\footnotesize\textit{Source: Authors' contribution.}}",
             r"\end{table}", ""]
    out = (RESULTS_DIR.parents[1] / "paper" / "ae_submission" / "si_body"
           / "_tab_lcoh_by_country.tex")
    out.write_text("\n".join(rows), encoding="utf8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
