"""The seasonal-storage geology classification the model applies, made visible.

The cavern set is a seven-item literal in scripts/merit_order_heat.py carrying a citation and
nothing else: no table, no working volume, no threshold. It is the most load-bearing input in
the paper, because the roughly EUR 50/MWh-heat difference between the two storage rates is
what separates the winning markets from the rest, and a reviewer reading either manuscript
could not see the classification at all.

Nothing here invents the cited source's geology. This writes out exactly what the model
applies -- the binary, the two rates, and the per-country charge they produce -- so a reader
who disputes either can see what turns on it.

Run:  cd code && PYTHONPATH=. python -m scripts.storage_geology
Out:  results/storage_geology.csv
      paper/ae_submission/si_body/_tab_storage_geology.tex
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

import src.Config as C
from src.Economics import (_seasonal_shift_fraction,
                           h2_seasonal_storage_adder_eur_mwh)
from scripts.merit_order_heat import (CAVERN, ETA_H2, MWH_PER_KG,
                                      STORE_CAVERN_EUR_KG, STORE_NONCAVERN_EUR_KG)

ROOT = Path(__file__).resolve().parents[2]

# Two boiler efficiencies are in play and the table has to show both, because an earlier
# version showed one and labelled it the other. The peaking arenas charge the full adder
# at ETA_H2 = 0.90, giving EUR 50 and EUR 100/MWh-heat, which is what every prose mention
# of the full adder quotes. The base-load levelised cost divides by the year-specific
# boiler efficiency instead, 0.92 at 2050, so its per-country charge is NOT the full
# adder times the shift fraction. Publishing 0.248 x 50 = 12.4 under a base-load heading
# next to prose reading 12.1 is what that mismatch produced. Both columns now come from
# the function that actually computes them, and the caption states both divisors.
ETA_H2_BASELOAD_2050 = 0.92


def build() -> pd.DataFrame:
    rows = []
    for c in sorted(C.EU_COUNTRIES):
        cav = c in CAVERN
        eur_kg = STORE_CAVERN_EUR_KG if cav else STORE_NONCAVERN_EUR_KG
        full = eur_kg / MWH_PER_KG / ETA_H2          # peaking convention, 0.90
        frac = _seasonal_shift_fraction(c)
        rows.append(dict(country=c, cavern=int(cav), store_eur_kg=eur_kg,
                         adder_full_eur_mwh_heat=round(full, 1),
                         load_derived_fraction=round(frac, 4),
                         adder_baseload_eur_mwh_heat=round(
                             h2_seasonal_storage_adder_eur_mwh(
                                 c, ETA_H2_BASELOAD_2050), 1)))
    return pd.DataFrame(rows)


def emit_si_table(df: pd.DataFrame) -> Path:
    cav_adder = df.loc[df.cavern == 1, "adder_full_eur_mwh_heat"].iloc[0]
    non_adder = df.loc[df.cavern == 0, "adder_full_eur_mwh_heat"].iloc[0]
    names = ", ".join(sorted(CAVERN))
    body = "\n".join(
        f"{r.country} & {'yes' if r.cavern else 'no'} & {r.store_eur_kg:.1f} & "
        f"{r.adder_full_eur_mwh_heat:.0f} & {r.adder_baseload_eur_mwh_heat:.1f} \\\\"
        for r in df.itertuples())
    tex = "\n".join([
        r"% Generated by scripts.storage_geology -- do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\footnotesize",
        # The caption names what is tabulated; the provenance and the two conventions go
        # into a Note block below the tabular, which is what the main paper does. At 222
        # words this caption was five times the corpus hard cap and no production editor
        # shortens a caption carrying 200 words of method.
        r"\caption{\textbf{The seasonal-storage classification the model applies, and the",
        rf"charge it produces, for all {len(df)} markets.}}}}",
        r"\label{tab:storage_geology}",
        r"\begin{tabular}{lcrrr}",
        r"\toprule",
        r"Country & Salt cavern & Rate (\euro{}/kg) & Full adder (\euro{}/MWh-heat)"
        r" & Base-load adder (\euro{}/MWh-heat) \\",
        r"\midrule",
        body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\par\vspace{3pt}{\footnotesize\raggedright",
        r"\textit{Note:} the cavern binary is a country-level reading of the mapped",
        r"salt-cavern potential of Caglayan and colleagues \citep{Caglayan2020caverns},",
        r"entered as a fixed list of seven and not derived by applying a working-volume",
        r"threshold to their maps. That reading is a judgement of ours. The source also maps",
        r"potential in Iberia, which we exclude as too small and too far from the demand",
        r"centres to serve a national heating role, and it maps France's potential in the",
        r"north alone, which we nonetheless credit to the whole country.",
        rf"The seven markets we classify as cavern are {names}. The two rates,",
        rf"\euro{{}}{STORE_CAVERN_EUR_KG:.1f} and \euro{{}}{STORE_NONCAVERN_EUR_KG:.1f}/kg at",
        r"roughly one cycle a year, are an assumption of this study and not a result of it,",
        rf"and the \euro{{}}{cav_adder:.0f} against \euro{{}}{non_adder:.0f}/MWh-heat difference",
        r"they produce is the largest single term separating the winning markets from the",
        r"rest. The base-load column charges each country the fraction of the full adder its",
        r"own winter-weighted load requires. The two columns divide the storage rate by",
        r"different boiler efficiencies, 0.90 in the two peaking arenas, which charge the",
        r"full adder, and the year-specific base-load efficiency of 0.92 at 2050, so the",
        r"base-load column is not the full adder multiplied by the shift fraction.",
        r"\par}",
        # \\ after \par} has no line to end. \vspace is the vertical-mode idiom.
        r"\vspace{2pt}{\footnotesize\textit{Source: Authors' contribution.}}",
        r"\end{table}",
        "",
    ])
    out = ROOT / "paper" / "ae_submission" / "si_body" / "_tab_storage_geology.tex"
    out.write_text(tex)
    return out


def main() -> None:
    df = build()
    csv = ROOT / "code" / "results" / "storage_geology.csv"
    df.to_csv(csv, index=False)
    tex = emit_si_table(df)
    print(df.to_string(index=False))
    print(f"\ncavern {int(df.cavern.sum())} of {len(df)}: {', '.join(sorted(CAVERN))}")
    print(f"full adder: cavern {df.loc[df.cavern == 1, 'adder_full_eur_mwh_heat'].iloc[0]:.0f}"
          f" vs non-cavern {df.loc[df.cavern == 0, 'adder_full_eur_mwh_heat'].iloc[0]:.0f}"
          f" EUR/MWh-heat")
    print(f"Wrote {csv}")
    print(f"Wrote {tex}")


if __name__ == "__main__":
    main()
